---
title: "산림치유"
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(fs)

dir_filename <- fs::dir_ls("data/성인대상, 산림치유 프로그램/")

paper_title <- fs::dir_ls("data/성인대상, 산림치유 프로그램/") |> 
 str_remove("data/") |> str_remove("\\.pdf") |> 
 str_remove("성인대상, 산림치유 프로그램/") 

paper_tbl <- dir_filename |> 
 enframe() |> 
 select(name) |> 
 mutate(논문명 = str_remove(name, "data/성인대상, 산림치유 프로그램/") |> str_remove("\\.pdf")) |> 
 mutate(파일크기 = map_dbl(name, ~fs::file_size(.)) /(1024^2) ) |> 
 mutate(파일크기 = round(파일크기, 1) ) |>
 select(-name)
 
paper_tbl |> 
 arrange(파일크기) |> 
 gt()
```


# 가설

```{r}
tribble(~"가설",
        "산림치유 프로그램은 참여자의 스트레스 및 우울감을 완화시키는데 긍정적인 영향을 미칠 것이다.",
        
        )
```


# 프롬프트

다음 사항을 논문에서 추출하여 json 형식으로 출력해줘.

1. 논문 제목
2. 논문 제출년월일
3. 논문 작성자
4. 논문 발행처
5. 검증하려는 가설

```{r}
paper_01 <- '{
  "title": "산림치유 프로그램이 스트레스 및 우울감 완화에 미치는 영향",
  "publicationDate": "2019년 10월",
  "author": "이 성 자",
  "publisher": "대전대학교 보건의료대학원",
  "hypothesis": "산림치유 프로그램은 참여자의 스트레스 및 우울감을 완화시키는데 긍정적인 영향을 미칠 것이다."
}'

paper_01_tbl <- jsonlite::fromJSON(paper_01) 

paper_01_tbl |> 
 as_tibble()

```

# 논문

```{r}
papers_tbl <- jsonlite::fromJSON("data/paper.json") 

papers_tbl |> 
 as_tibble()

```

# 가설검정 방법론

가설검정을 위해 사용된 통계적 방법론은 뭐야?



